language: java
sudo: false
install: true

jdk:
#  - openjdk7 (can't use it since some dependencies required java 8)
  - openjdk8

script:
  - mvn clean verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
    except:
        - gh-pages

notifications:
  email: true
